name = "Unwrap"
uuid = "66ceed60-733c-11e9-33de-751f162d5676"
authors = ["platawiec"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test=["Test"]

[compat]
julia = "^1.0"